version: '3.1'

services:

  rails:
    image: rails
    container_name: rails
    restart: always
    expose:
      - "80"
    ports:
      - "80"
    volumes:
      - ./:/home/app
    env_file:
      - docker.env

  db:
    image: mariadb
    container_name: rails_db
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql:/var/lib/mysql
    env_file:
      - docker.env
