default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: <%= "#{ENV['DB_NAME']}_test" %>

development:
  <<: *default
  database: <%= "#{ENV['DB_NAME']}_development" %>

production:
  <<: *default
